[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0x0304ded57a32270ddcc98ad04e3e4c6be8a141fd01f54e0fea08dd69a5268518'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]